### ISSUE TITLE
新增基金会变成空白

### ISSUE THREAD

**Issue by GuanKay** [1zilc/fishing-funds#101]
### BUG截图:  
![image](https://user-images.githubusercontent.com/65692776/124706944-abddea80-df2a-11eb-9639-d9e613ae9b37.png)

**Comment by 1zilc** [comment]
提供一下 JSON 配置

**Comment by GuanKay** [comment]
[
  { "name": "中欧医疗健康混合C", "cyfe": 337.12, "code": "003096" },
  { "name": "招商中证白酒指数(LOF)", "cyfe": 781.44, "code": "161725" },
  { "name": "招商中证白酒指数(LOF)C", "cyfe": 686.86, "code": "012414" },
  { "name": "汇丰晋信智造先锋股票C", "cyfe": 245.92, "code": "001644" },
  { "name": "工银新能源汽车混合C", "cyfe": 0, "code": "005940" },
  { "name": "南方中证全指证券公司ETF联接C", "cyfe": null, "code": "004070" },
  { "name": "广发中证军工ETF联接C", "cyfe": 901.79, "code": "005693" },
  { "name": "诺安成长混合", "cyfe": null, "code": "320007" }
]

**Comment by GuanKay** [comment]
[
  { "name": "中欧医疗健康混合C", "cyfe": 337.12, "code": "003096" },
  { "name": "招商中证白酒指数(LOF)", "cyfe": 781.44, "code": "161725" },
  { "name": "招商中证白酒指数(LOF)C", "cyfe": 686.86, "code": "012414" },
  { "name": "汇丰晋信智造先锋股票C", "cyfe": 245.92, "code": "001644" },
  { "name": "工银新能源汽车混合C", "cyfe": 0, "code": "005940" },
  { "name": "南方中证全指证券公司ETF联接C", "cyfe": null, "code": "004070" },
  { "name": "广发中证军工ETF联接C", "cyfe": 901.79, "code": "005693" },
  { "name": "诺安成长混合", "cyfe": null, "code": "320007" }
]

**Comment by 1zilc** [comment]
#131 4.4.0已修复该问题，感谢反馈！
