### ISSUE TITLE
BUG反馈：添加基金时成本价的精确度问题

### ISSUE THREAD

**Issue by lirycoac** [1zilc/fishing-funds#111]
### Fishing Funds版本号:  
4.2.1

### 操作系统平台及版本号:  
MacOS Big Sur 11.4

### BUG截图:  
![image](https://user-images.githubusercontent.com/17177377/125219630-abad6880-e2f7-11eb-9dae-d75483ae0502.png)

### 详细描述:  
**添加新基金**时，输入小数点后四位的成本价后被截到了小数点后两位。之后再去修改成本价时是正常的。

**Comment by 1zilc** [comment]
感谢反馈，下个版本将修复该bug

**Comment by 1zilc** [comment]
#117 4.3.0 已修复
