### ISSUE TITLE
希望Mac将菜单栏图标 换成 当日估算收益/收益率

### ISSUE THREAD

**Issue by dabenliu** [1zilc/fishing-funds#128]
### 详细描述:  
希望增加设置，可以将菜单栏的大F图标 换成实时的 收益估值 或者预估收益率 
样式可以参考软件iStat Menus中的网速显示 

功能可以参考
Chrome插件 -> 设置 -> 角标显示 -> 日收益、日收益率
https://chrome.google.com/webstore/detail/%E5%B0%8F%E5%9F%BA%E5%8A%A9%E6%89%8B-%E6%97%B6%E5%88%BB%E5%85%B3%E6%B3%A8%E4%BD%A0%E7%9A%84%E5%9F%BA%E9%87%91/jikclepdllhnflmfbchiepgkhcdkddgb?hl=zh-CN

**Comment by 1zilc** [comment]
#131 4.4.0已添加该功能，十分感谢反馈！
