### ISSUE TITLE
添加分组展示

### ISSUE THREAD

**Issue by irisiberia** [1zilc/fishing-funds#139]
### 详细描述: 能不能有一个分组管理，把相关行业的基金或者股票放在一个分组里面展示

**Comment by 1zilc** [comment]
按行业分组，这个要看下天天的接口有没有相关字段，如果有的话后续版本可以加入这个功能

**Comment by 1zilc** [comment]
很抱歉天天的接口返沪中没有相关字段，这个无法实现了
