### ISSUE TITLE
Mac m1 启动时显示安装包已损坏

### ISSUE THREAD

**Issue by Zhao0396** [1zilc/fishing-funds#149]
### BUG截图:  
![image](https://user-images.githubusercontent.com/39544899/128314233-92b1586e-f6e9-4e90-9d66-c8117e536dd3.png)

**Comment by 1zilc** [comment]
https://github.com/1zilc/fishing-funds#%E4%B8%8B%E8%BD%BD%E4%BD%BF%E7%94%A8

**Comment by Qetesh** [comment]
最近几个版本的arm版本都打不开，按照链接看过已经是“允许任何来源”，没有看到“仍然打开”。

**Comment by Qetesh** [comment]
> https://github.com/1zilc/fishing-funds#%E4%B8%8B%E8%BD%BD%E4%BD%BF%E7%94%A8

最近几个版本的arm版本都打不开，按照链接看过已经是“允许任何来源”，没有看到“仍然打开”。

**Comment by Zhao0396** [comment]
![image](https://user-images.githubusercontent.com/39544899/128446589-89e50d0a-dd52-4d0e-9c48-4c1040211296.png)

**Comment by 1zilc** [comment]
那我再排查一下

**Comment by 1zilc** [comment]
重新安装，试过吗？

**Comment by Zhao0396** [comment]
我先用的是从Macwk里下载的，可以使用。之前也有过多吃重装

**Comment by AsuraLG** [comment]
我的系统版本和软件版本也是一样的，也出现了这样的报错

**Comment by Aliom252181** [comment]
需要加一个签名，下载https://macwk.com/soft/macos-assistant-macwk这个软件然后在
![image](https://user-images.githubusercontent.com/49222345/128460330-f783d4c5-0985-40d8-89e8-acd44f1615ba.png)
里面给Fishing Funds加个签名就好了。

**Comment by 1zilc** [comment]
aplle的企业证书签名目前搞不定，构建的时候无法公证

**Comment by macwkcom** [comment]
如果用小助手的话不需签名操作，签名需要安装苹果 command line tool 开发者工具。只需要使用绕过签名即可。macwk 网站上下载安装 fishing-funds 时候都会自动执行此操作进行修复的，所以不会有这个问题。

**Comment by 1zilc** [comment]
> 如果用小助手的话不需签名操作，签名需要安装苹果 command line tool 开发者工具。只需要使用绕过签名即可。macwk 网站上下载安装 fishing-funds 时候都会自动执行此操作进行修复的，所以不会有这个问题。

感谢macwk官方的说明

**Comment by wizyoung** [comment]
终端执行 sudo xattr -d com.apple.quarantine "/Applications/Fishing Funds.app" 就好

**Comment by maxisvest** [comment]
> 终端执行 sudo xattr -d com.apple.quarantine "/Applications/Fishing Funds.app" 就好

That's it

**Comment by visibleLi** [comment]
> 

有用

**Comment by vaynevayne** [comment]
> 需要加一个签名，下载https://macwk.com/soft/macos-assistant-macwk 这个软件然后在 ![image](https://user-images.githubusercontent.com/49222345/128460330-f783d4c5-0985-40d8-89e8-acd44f1615ba.png) 里面给Fishing Funds加个签名就好了。

挂了么? 打不开

**Comment by Qetesh** [comment]
> > 需要加一个签名，下载https://macwk.com/soft/macos-assistant-macwk 这个软件然后在 ![image](https://user-images.githubusercontent.com/49222345/128460330-f783d4c5-0985-40d8-89e8-acd44f1615ba.png) 里面给Fishing Funds加个签名就好了。
> 
> 挂了么? 打不开

可以通过快捷键command + 空格，搜索终端。在终端中输入`xattr -r -d com.apple.quarantine /Applications/Fishing\ Funds.app`

**Comment by Wayne-007** [comment]
感谢大佬，终于成功了！
M系列不用arm版本真的好卡，卡爆了，影响我赚钱了😭
