### ISSUE TITLE
股票

### ISSUE THREAD

**Issue by devYoungyang** [1zilc/fishing-funds#152]
1.股票里展示公司概况
2.股价达到预定值提醒
3.展示从添加到自选时刻起到截至目前的收益率

**Comment by 1zilc** [comment]
#154 4.5.0 已添加公司概况

**Comment by devYoungyang** [comment]
1建议添加操盘必读：市盈率，市净率，每股净资产，每股收益，营业总收入，净利润，毛利率，总市值，营收同比，净利润同比，净利率，负债率，等等 
2.公司概况具体展示形式：公司名称，a股代码，h股代码，所属区域，所属行业，所属概念，董事长，法人代表，成立日期，注册资本，主营业务，等等
具体展示内容可以参考东方财富

**Comment by 1zilc** [comment]
各个地区股票接口返回的内容不一样，很难做到统一，东财的接口你可以参考 [这里](https://github.com/1zilc/fishing-funds/blob/fa4a40becfe174aca85bc2f8c9a7febc5d4082cf/src/renderer/services/stock.ts#L503) ，不同接口返回的共同字段很少，且大部分我觉得没什么展示意义

**Comment by 1zilc** [comment]
最主要的问题还是东财自己本身接口就不统一

**Comment by devYoungyang** [comment]
好的
