### ISSUE TITLE
添加特定基金代码时，计算预估收益会显示NaN

### ISSUE THREAD

**Issue by blackwingss** [1zilc/fishing-funds#153]
### Fishing Funds版本号:  
4.4.2
### 操作系统平台及版本号:  
OS X 10.15.7
### BUG截图:  
![image](https://user-images.githubusercontent.com/17474950/128463842-9c713a62-a054-4981-9dc7-17d3b4462ef2.png)

### 详细描述:  
添加012975这只🐔时会导致计算的预估收益显示异常

**Comment by 1zilc** [comment]
#154 4.5.0 已修复
