### ISSUE TITLE
估算值错误，导致计算收益错误~

### ISSUE THREAD

**Issue by indextank** [1zilc/fishing-funds#17]
### Fishing Funds版本号:  
2.20
### 操作系统平台及版本号:  
win 10
### BUG截图:  
![image](https://user-images.githubusercontent.com/6389841/109388454-18742780-7942-11eb-9c33-48cb23756210.png)

### 详细描述:  
估算值不对，设置中切换不同的基金，估算值都不一样。导致实际收益跟支付宝里面比对，有差异。

**Comment by 1zilc** [comment]
因为之前的设计没有考虑当天3点后的实际收益更新情况，就会导致一个问题，即当天实际收益数据只能第二天才能看到，而当天只能看到各平台当天的估算值，这个问题我会逐步解决，感谢您的支持和反馈！

**Comment by 1zilc** [comment]
#22 使用2.5.0版本，已支持当日净值自动查询

**Comment by fwh1990** [comment]
@1zilc 请问作者，能否加一个 蚂蚁财富 的基金数据来源？目前已有的基金数据来源和支付宝里的基金数据都对不上，痛苦啊。

再次感谢作者
