### ISSUE TITLE
建议功能

### ISSUE THREAD

**Issue by indextank** [1zilc/fishing-funds#18]
### 详细描述:  
1、详情里面建议加上历史净值和历史业绩，尤其是历史净值，太重要了。
2、在保持现有排序功能的基础上，建议加上基金拖动排序功能，并且记忆~方便自定义排序。
3、主界面字体较小，建议设置中加入字体大小设置功能，便于用户根据自身需求调整字体大小。
4、建议加上基金的具体介绍、基金经理概况、基金的分析指标展示（收益能力、最大回撤、夏普比例、标准差）
5、后期可以考虑加上黑色主题元素

**Comment by 1zilc** [comment]
十分感谢您提出的宝贵意见，我挨个回复一下：
1. 确实漏掉了这个数据，现在已经做了一半了
2. 暂时未做，后期将添加
3. 暂时未做，后期将添加
4. 这些数据尽量拿，能拿到的都将逐步展示
5. 这个懂得都懂，低调模式将会在2.3.0版本上线

最后再次感谢老哥的宝贵意见🙏，谢谢！
