### ISSUE TITLE
货币基金收益计算错误

### ISSUE THREAD

**Issue by Youngmiyo** [1zilc/fishing-funds#182]
### BUG截图:  
<img width="298" alt="FF页面" src="https://user-images.githubusercontent.com/27180765/131105015-21843ddf-4528-43e2-9ac4-947ad83cb08d.png">
<img width="298" alt="支付宝页面" src="https://user-images.githubusercontent.com/27180765/131105298-bc7b04d7-399b-4531-a6f6-7285525775b9.jpg">)

### 详细描述:  
货币基金的计算方式与其它基金不一样，更新的净值是**万分收益**

**Comment by 1zilc** [comment]
了解了一下，万份收益的计算方式还是 份额 * 净值，但是净值貌似是不变的，一直都是 1 ，所以是份额在每日增多，这样子的话，还是挺麻烦的，每天都要重新录入份额

**Comment by Youngmiyo** [comment]
> 了解了一下货币基金的计算方式还是 份额 * 净值，但是净值貌似是不变的，一直都是 1 ，所以是份额在每日增多，这样子的话，还是挺麻烦的，每天都要重新录入份额

是的，API如果能直接获取每日更新的**万份收益**的话应该就没问题，计算方式应该为**现有份额*净值1/10000*当日更新的万份收益**
如果是周末，**周末的万份收益**得周一才会更新，这个可能就需要一定的判断了

没关系，要不要都行，加上显得更完善些🤣

**Comment by Youngmiyo** [comment]
> 了解了一下货币基金的计算方式还是 份额 * 净值，但是净值貌似是不变的，一直都是 1 ，所以是份额在每日增多，这样子的话，还是挺麻烦的，每天都要重新录入份额

如果可以的话，最好能**自动更新份额**，好像有点小麻烦😅

**Comment by 1zilc** [comment]
自动份额这个，除非接入支付宝，从后台拿数据，目前来说，是无法实现的。

**Comment by 1zilc** [comment]
[4.7.5](https://github.com/1zilc/fishing-funds/releases/tag/v4.7.5) 我修复了持有收益和收益率，当天的收益由于是份额在变，所以没法自动计算了，所以货币基金看不了当日收益，只能看持有收益

**Comment by Youngmiyo** [comment]
> [4.7.5](https://github.com/1zilc/fishing-funds/releases/tag/v4.7.5) 我修复了持有收益和收益率，当天的收益由于是份额在变，所以没法自动计算了，所以货币基金看不了当日收益，只能看持有收益

👌🏻那我每天自己输入份额就好了

**Comment by 1zilc** [comment]
那我先关闭了哈
