### ISSUE TITLE
希望钱包功能可以支持股票计算

### ISSUE THREAD

**Issue by Hyejeongdd** [1zilc/fishing-funds#196]
### 详细描述:  
希望钱包功能可以支持股票持仓成本 目前收益计算

**Comment by 1zilc** [comment]
感谢反馈，后续提供支持

**Comment by W-quan** [comment]
+1

**Comment by 1zilc** [comment]
感谢建议，[8.0.0](https://github.com/1zilc/fishing-funds/releases/tag/v8.0.0) 已支持该功能
