### ISSUE TITLE
貌似不能添加QDII类型基金

### ISSUE THREAD

**Issue by liukevin0001** [1zilc/fishing-funds#198]
### BUG截图:  
<img width="291" alt="image" src="https://user-images.githubusercontent.com/89888694/131602546-24ecb22c-5ad9-4586-8503-bca1fa0fa5bc.png">

### 详细描述:  
貌似不能添加QDII类型基金，尝试更换同类型其他基金显示同样问题提示，谢谢

**Comment by 1zilc** [comment]
请使用 新版本的Fishing Funds ，

**Comment by 1zilc** [comment]
2.7.0 版本不支持QDII

**Comment by liukevin0001** [comment]
谢谢，已经解决，不好意思打扰您了～

**Comment by 1zilc** [comment]
不客气
