### ISSUE TITLE
希望可以改进虚拟货币的展示

### ISSUE THREAD

**Issue by jiangxiaolin1995** [1zilc/fishing-funds#208]
### 详细描述:  
希望虚拟货币可以接入货币或者币安的接口，数据更准确
希望可以加入虚拟货币持股

**Comment by 1zilc** [comment]
感谢反馈，目前币安的接口api.binance.com 国内貌似无法访问了，虚拟货币持股和股票一样将会在后续版本中支持

**Comment by jiangxiaolin1995** [comment]
非常感谢您的回复～
我是觉得可以加入币安，因为还是很多人会科学上网
不清楚火币和ok有没有对应的接口可以加入
再次感谢您的回复

**Comment by 1zilc** [comment]
不具备普遍性的功能暂时不打算接入
