### ISSUE TITLE
管理界面加上所属钱包位置转移

### ISSUE THREAD

**Issue by blackwingss** [1zilc/fishing-funds#211]
### 详细描述:  
希望可以加上在基金管理界面里单选或者多选一些基金转移到别的钱包的功能！！！

**Comment by 1zilc** [comment]
感谢反馈，这个操作存在不同钱包同一只基持仓成本不同的冲突，建议还是用JSON导入导出的方式自行修改

**Comment by blackwingss** [comment]
如果不同钱包存在相同的基金则要么提醒，要么转移按钮是灰色的，类似这种方案不知道可行吗？如果是独一无二的基金则直接转移成功这样。

**Comment by 1zilc** [comment]
#209 已提供单基金json复制，推荐使用json导入
