### ISSUE TITLE
vscode 运行项目报错无法启动

### ISSUE THREAD

**Issue by hejun-lyne** [1zilc/fishing-funds#212]
Hi，我尝试在vscode里面运行项目，始终无法成功，希望能得到协助：
`
> fishing-funds@ start:main /Users/admin/Documents/git/my-funds
> cross-env NODE_ENV=development && electron -r ts-node/register ./src/main/main.dev.ts
/Users/admin/Documents/git/fishing-funds/node_modules/electron/dist/Electron.app/Contents/MacOS/Electron exited with signal SIGSEGV
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! fishing-funds@ start:main: `cross-env NODE_ENV=development && electron -r ts-node/register ./src/main/main.dev.ts`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the fishing-funds@ start:main script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/admin/.npm/_logs/2021-09-08T02_48_00_564Z-debug.log
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
终端进程“bash '-c', 'yarn run start:renderer'”已终止，退出代码: 1。
终端将被任务重用，按任意键关闭。
`

这是我的运行环境：
`
$ node -v
v14.17.6
$ npm -v
6.14.15
$ yarn -v
1.22.10
`

**Comment by 1zilc** [comment]
1. 尝试删除node_modules
2. 重新执行 `yarn install`
3. 确保依赖安装成功
4. 重新执行 `yarn start`

**Comment by hejun-lyne** [comment]
好像找到原因了，webpack好像依赖了tapable，package.json里面没有这个依赖，我安装就可以了
`yarn add tapable --dev`
