### ISSUE TITLE
无法自动刷新

### ISSUE THREAD

**Issue by EnochWangYH** [1zilc/fishing-funds#215]

**Comment by 1zilc** [comment]
方便的话提供一下全局配置文件
![image](https://user-images.githubusercontent.com/44715458/132620411-8ff2c710-6de6-4dff-a65b-7b2fa95ca7b7.png)

**Comment by EnochWangYH** [comment]
附件为全局配置


| |
Enoch
|
|
***@***.***
|
签名由网易邮箱大师定制


在2021年09月10日 ***@***.***> 写道：
附件为全局配置


| |
Enoch
|
|
***@***.***
|
签名由网易邮箱大师定制


在2021年09月9日 ***@***.***> 写道：

方便的话提供一下全局配置文件


—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

从网易邮箱大师发来的云附件
Fishing-Funds-Backup-1631243403701.ff(5.17MB,2021年9月25日 11:12 到期)
下载

**Comment by 1zilc** [comment]
#209 尝试使用4.8.0
