### ISSUE TITLE
apple m1 版本显示安装包已损坏

### ISSUE THREAD

**Issue by yuzhenghuan** [1zilc/fishing-funds#218]
### Fishing Funds 版本号
4.8.0 arm64
### 操作系统平台及版本号
macos bigsur 10.15.2
### BUG 截图
<img width="260" alt="WX20210913-202626@2x" src="https://user-images.githubusercontent.com/43665741/133083192-5494711e-4a16-4eb1-a64d-94589295f24c.png">

### 详细描述
软件显示损坏

**Comment by 1zilc** [comment]
#149
