### ISSUE TITLE
关于增加基金估值的显示及提醒

### ISSUE THREAD

**Issue by jkYangIOP** [1zilc/fishing-funds#222]
### 详细描述
现在的小程序已经非常不错了，首先感谢作者的付出与贡献。在使用过程中，我有以下两个小建议。在添加自选后，基金仅能够查看到预估的涨跌幅，但是没有净值估算（也有可能是我没有找到），希望能够实时显示净值估算。另外在自选的基金里可以设置涨跌幅提醒，这个功能很不错，是否能考虑也添加一个到达净值估算的提醒呢？这样方便在当天就买入。再次感谢作者的付出！

**Comment by geeklihui** [comment]
净值估算在详情里有

**Comment by 1zilc** [comment]
#298 5.3.0 已支持净值提醒
