### ISSUE TITLE
这个内存占用有点高啊  能优化么，apple m1版本

### ISSUE THREAD

**Issue by yuzhenghuan** [1zilc/fishing-funds#223]
### 详细描述
<img width="925" alt="WX20210915-175734@2x" src="https://user-images.githubusercontent.com/43665741/133413246-c3e0d21d-14a2-4c61-9d4e-733891c9d78e.png">

**Comment by 1zilc** [comment]
感谢反馈，现版本确实存在内存泄露问题，将会在下个版本中修复，再次感谢🙏

**Comment by 1zilc** [comment]
#221 已修复
