### ISSUE TITLE
软件报错，无法添加基金

### ISSUE THREAD

**Issue by heguohui2018** [1zilc/fishing-funds#25]
<img width="585" alt="Screen Shot 2021-03-24 at 10 51 22" src="https://user-images.githubusercontent.com/35359288/112247299-08284180-8c8f-11eb-9422-7273f648ced3.png">

**Comment by 1zilc** [comment]
我试试看能不能兼容一下这种基，可以查看基金详情，但是估值数据拿不到就没办法咯。感谢反馈 :)🙏

**Comment by heguohui2018** [comment]
作者你好，我感觉你做的这个功能不错，就是有个小问题需要基金一多的话，不停的向下滑动查看每支基金，有点累，

<img width="601" alt="Screen Shot 2021-03-26 at 07 42 29" src="https://user-images.githubusercontent.com/35359288/112557285-1731ff80-8e07-11eb-9a7a-a9f2555d408a.png">

嫩否添加一个基金组合功能，比方说在支付宝，京东分别买不同的基金，然后同时在这个软件上分别创建不同的分组方便管理

**Comment by heguohui2018** [comment]
Thank you

**Comment by 1zilc** [comment]
我现在不清楚的是不同分组能否添加相同基，如果分组的话，应该也会有单独的分组收益等等。你能帮忙补充一下我开发起来会更顺畅，:)
