### ISSUE TITLE
无法添加加密货币

### ISSUE THREAD

**Issue by Chuhan1112** [1zilc/fishing-funds#269]
### Fishing Funds 版本号
5.1.0
### 操作系统平台及版本号
macOS 11.6
### BUG 截图

<img width="291" alt="截屏2021-10-28 下午3 26 30" src="https://user-images.githubusercontent.com/35064712/139207330-af24581b-0cc3-4922-9f80-089a111c3e87.png">

### 详细描述
点击`自选`没有反应，自选列表也没有添加成功

**Comment by 1zilc** [comment]
![image](https://user-images.githubusercontent.com/44715458/139614241-2d106bc1-ad19-41ac-bba7-366c128b552f.png)

**Comment by B0y1n4o4** [comment]
同无法添加加密货币。不使用代理，无法使用货币榜功能，使用HTTP代理，货币榜正常使用，币详情可以正常查看，添加货币搜索框搜索无结果，疑似没走流量。设置全局代理，货币榜仍然正常使用，搜索框仍然无法搜索添加。 @1zilc

**Comment by 1zilc** [comment]
> 同无法添加加密货币。不使用代理，无法使用货币榜功能，使用HTTP代理，货币榜正常使用，币详情可以正常查看，添加货币搜索框搜索无结果，疑似没走流量。设置全局代理，货币榜仍然正常使用，搜索框仍然无法搜索添加。 @1zilc

<img width="361" alt="image" src="https://user-images.githubusercontent.com/44715458/152714964-dfec4c3a-46d5-4035-9b82-e133799c52e9.png">
经测试，能搜索

**Comment by fy5220** [comment]
> 

完全一样= =
