### ISSUE TITLE
增加场内基金数据

### ISSUE THREAD

**Issue by 15190076996** [1zilc/fishing-funds#270]
### 详细描述
希望能动态追踪场内基金

**Comment by 1zilc** [comment]
经测试，场内基金可以正常添加，并显示估值
![image](https://user-images.githubusercontent.com/44715458/139613965-0d62aa12-5660-414f-839b-016c177fcf82.png)

**Comment by 1zilc** [comment]
或者提供一下相关基金代码

**Comment by 15190076996** [comment]
![image](https://user-images.githubusercontent.com/12581787/139783467-b0f7afc2-e0e4-4229-b7ce-748d2fa58f6b.png)
计算出来的估值，有偏差。场内基金可能用股票方式更好

**Comment by 1zilc** [comment]
估算值本身是有偏差的，所有数据来自你所选择的第三方数据源，你可以选择相对准确的源。
