### ISSUE TITLE
希望可以汇总钱包中各基金的板块分布和所有基金持仓汇总

### ISSUE THREAD

**Issue by kercylan98** [1zilc/fishing-funds#271]
### 详细描述
希望可以汇总钱包中各基金的板块分布和所有基金持仓汇总

**Comment by 1zilc** [comment]
感谢反馈，点子很不错，实现起来有难度，很多数据太分散了，接口调用太多。只能试试看

**Comment by kercylan98** [comment]
收到

**Comment by 1zilc** [comment]
#278 v5.2.0统计中已添加基金持仓汇总，板块数据获取起来太多了，感觉意义也不怎么大就没加了哈，感谢反馈。
