### ISSUE TITLE
估值净值更新后在首页不计算收益

### ISSUE THREAD

**Issue by xslczx** [1zilc/fishing-funds#272]
### 详细描述

该基金在首页没有计算收益显示0%，在详情虽然没有历史净值列表数据，但是有今日的日涨跌幅和净值，是否可以加以估算

**Comment by 1zilc** [comment]
QDII类型由于没有估值时间，所以即使有净值，也没法做比较

**Comment by 1zilc** [comment]
无法在当日估算收益，只能等第二个交易日更新持有收益。

**Comment by xslczx** [comment]
了解，但是第二天也没有更新所以很奇怪，希望可以改善

**Comment by 1zilc** [comment]
是第二个交易日更新哈，不一定是第二天，还请检查一下，应该是没问题的
