### ISSUE TITLE
希望加入一个窗口拖动的功能

### ISSUE THREAD

**Issue by 1445453337** [1zilc/fishing-funds#275]

**Comment by 1zilc** [comment]
反复考虑后还是暂时保持现有的menubar逻辑，感谢你的意见

**Comment by JoeyLearnsToCode** [comment]
> 反复考虑后还是暂时保持现有的menubar逻辑，感谢你的意见

**Comment by 1zilc** [comment]
> > 反复考虑意见后还是暂时保留现有的菜单栏逻辑，谢谢你的
> 
> 菜单栏可以加一个固定按钮（pin）吗？开启后，在失去焦点时不消失，这样在需要的时候可以常开盯盘

设置里面有一个「总是置顶」，应该可以满足
