### ISSUE TITLE
谢谢作者，很好用，是否考虑一下备份恢复功能？

### ISSUE THREAD

**Issue by geeklihui** [1zilc/fishing-funds#28]
### 详细描述:  
买的🐔比较多，多设备用户表示蛋疼，每次都要一个个加一遍。考虑到重装系统等，也是挺麻烦的，是否可以考虑一下数据的导出、导入，备份恢复咧？谢谢~

**Comment by 1zilc** [comment]
2.7.0 版本已经支持数据导出哦
![image](https://user-images.githubusercontent.com/44715458/116337072-2e03b180-a80c-11eb-90ea-01995abeb4b2.png)

**Comment by geeklihui** [comment]
谢谢~
