### ISSUE TITLE
没有持仓信息的基金无法添加自选

### ISSUE THREAD

**Issue by vincentyang116** [1zilc/fishing-funds#29]
### BUG截图:  
<img width="310" alt="image" src="https://user-images.githubusercontent.com/38676561/117332574-96b4f300-aeca-11eb-8b94-4b32de2f8e6e.png">

### 详细描述:  
添加如图基金时提示找不到，这是选择天天基金时的搜索结果，测试其他来源有可以添加的，但是无法更新净值。如图基金暂时没有持仓信息，但是在天天基金上净值每天更新。

**Comment by 1zilc** [comment]
这个基在天天上没有估值，按照当前的收益计算逻辑，暂时还没办法纳入自选当中，还请谅解🙏
![image](https://user-images.githubusercontent.com/44715458/117432188-a9780800-af5c-11eb-9182-bda205ed2126.png)

**Comment by vincentyang116** [comment]
没关系, 程序功能很棒. 另外我发现CPU占用有点高, 能改善一下就更好了

**Comment by 1zilc** [comment]
cpu问题我研究一下，后续会优化改进，再次感谢哈 :)
