### ISSUE TITLE
添加部分QDII基金是报错

### ISSUE THREAD

**Issue by chengping01** [1zilc/fishing-funds#30]
### Fishing Funds版本号:  
V2.7.0

### 操作系统平台及版本号:  
Mac OS Big Sur 11.3.1

### BUG截图:  
![image](https://user-images.githubusercontent.com/75122076/117451487-2c0cc180-af75-11eb-977a-c23eb7e7cfa6.png)

### 详细描述:  
添加部分QDII基金时，可以搜到基金信息，但是添加失败
尝试更换多个数据源均未成功

**Comment by 1zilc** [comment]
https://github.com/1zilc/fishing-funds/issues/25#issuecomment-806865244

**Comment by ttc9082** [comment]
遇到相同的问题。看来没办法了。开发者做的不错感谢。
