### ISSUE TITLE
全部钱包总览

### ISSUE THREAD

**Issue by Wooele** [1zilc/fishing-funds#306]
### 详细描述
目前基金页面各个钱包是需要切换才能查看的，希望增加全览能力。(新增个全部钱包)
![image](https://user-images.githubusercontent.com/83322457/143377184-6df04743-19b7-4b7c-ab04-e9a761a51ef8.png)

**Comment by 1zilc** [comment]
感谢反馈，因为这里的钱包还和导入导出，刷新等功能有关，所以此处的逻辑耦合较高，实现”全部“改动较大，建议还是在基金统计里面看全部基金
