### ISSUE TITLE
能否在【非简洁模式】下直观显示基金持有收益率

### ISSUE THREAD

**Issue by geeklihui** [1zilc/fishing-funds#316]
### 详细描述
如题，现在【非简洁模式】下是两行，第一行左边是基金名称，右边是当日（预估）涨幅；而第二行左边是代码、更新日期。没有显示持有收益率，其实这个还是蛮重要的，而且基金也支持按照持有收益率排序，却无法直观的看到每只基金的持有收益率，都要点一下才能看到。
第二行左边更新日期后，还挺空的，加上持有收益率应该也不会太影响美观度。把净值更新移动到第一行最后。（小小的吐槽一下，这个净值更新的框比持有的框大一圈...）右边也可以加，就是涨幅这个框要上移一些。
我做了个大概的效果图，供参考：
![FF-N](https://user-images.githubusercontent.com/28993319/145240830-45a4bae4-1a0b-442b-990f-2252b5d67ab7.png)

**Comment by 1zilc** [comment]
感谢反馈，可以点击此处展开所有
![image](https://user-images.githubusercontent.com/44715458/145329702-f4cc1e4d-ae40-4f50-8f76-593f53a4b683.png)
