### ISSUE TITLE
不通平台收益不通的原因是什么

### ISSUE THREAD

**Issue by yusinan0119** [1zilc/fishing-funds#317]
### Fishing Funds 版本号
5.3
### 操作系统平台及版本号
MacOS 12.0.1 
### 详细描述

想请教一下，切换不通的平台为何收益不一致，比如设置天天基金为数据来源，显示收益为167，切换为支付宝变为147，切换为腾讯则为120，同花顺为150.想问一下这差价的原因是什么？谢谢指导！

**Comment by 1zilc** [comment]
不同平台估值不同
