### ISSUE TITLE
希望加入闲散资金的条目或钱包

### ISSUE THREAD

**Issue by gunaiqiu** [1zilc/fishing-funds#322]
### 详细描述
好应用！已经习惯用这个应用管理来管理投资的那些产品和股票了。在买基金和股票的时候，留了些闲钱还在资金账户里的，还在余额宝里的，还在卡里睡着的。希望能有一个闲散资金的条目或钱包，统计总金额的时候能知道还有多少闲钱可以用，总资产也能这么看出来就挺好了。

**Comment by 1zilc** [comment]
感谢你的建议，但是抱歉，FF仅作为基金估值工具不提供闲散资金统计。请使用其他方式统计管理你的资产
