### ISSUE TITLE
添加的基金莫名消失

### ISSUE THREAD

**Issue by Erbeter** [1zilc/fishing-funds#33]
### BUG截图:  
![image](https://user-images.githubusercontent.com/42734176/118229261-4804eb80-b4be-11eb-8066-9130dde2b33f.png)
![image](https://user-images.githubusercontent.com/42734176/118229296-56eb9e00-b4be-11eb-9f53-4dfa6bc8c219.png)

**Comment by 1zilc** [comment]
你看下多刷几次能不能出来，如果可以的话就可能是基金添加多了，并发请求的时候天天基金那边没有返回数据，我优化一下请求
