### ISSUE TITLE
Apple M1芯片 + arm64架构node16编译失败，提示lzma-native编译不通过

### ISSUE THREAD

**Issue by and80506** [1zilc/fishing-funds#333]
### Fishing Funds 版本号
git branch master
### 操作系统平台及版本号
Mac OS Monterey 12.0.1
### BUG 截图
--
### 详细描述
Mac Apple M1 + node16下 npm install时提示依赖lzma-native构建失败，排查后应该是lzma-native未提供arm64二进制包，详细见https://github.com/addaleax/lzma-native/issues/118。

nvm 安装node15版本解决。   另外node10经测试无法兼容webpack-dev-server（最低12版本），建议将package.json的node版本检查更新至>=12.x

**Comment by 1zilc** [comment]
感谢建议，已修改
