### ISSUE TITLE
可关闭顶部栏收益金额

### ISSUE THREAD

**Issue by AdorableLi** [1zilc/fishing-funds#341]
不知道是我没找到设置，还是暂时没有开发这个设置，目前顶部栏的当日收益金额貌似是不能关闭的。
如果是没有开发的话，老哥整一个开关吧，最近跌的实在难受，软件都不敢开，看见那明晃晃的数字，连特么班都没心思上。

**Comment by 1zilc** [comment]
![image](https://user-images.githubusercontent.com/44715458/149147556-6ff990a3-a794-4188-89ad-43edc6fee7e0.png)
