### ISSUE TITLE
希望托盘栏的收益展示能区分颜色

### ISSUE THREAD

**Issue by DumKing** [1zilc/fishing-funds#348]
### 详细描述
首先非常感谢作者的开源，大大的赞 👍👍👍
以下是我的一点小建议：
![image](https://user-images.githubusercontent.com/41665000/149296310-a369d814-e52e-40c0-9d39-95ecd5c4d178.png)
如图，现在菜单栏收益是统一的颜色，希望能区分颜色，同其它地方一致， 负数展示为绿色，正数展示为红色

**Comment by 1zilc** [comment]
你好，[electron-api](https://www.electronjs.org/docs/latest/api/tray#traysettitletitle-options-macos) 未提供相关配置实现颜色区分
