### ISSUE TITLE
不知是否可以支持方便地查看多个钱包总收益情况

### ISSUE THREAD

**Issue by lirycoac** [1zilc/fishing-funds#352]
### 详细描述

设置了不同的钱包，希望能够比较方便地看到总的收益情况。以前常是打开后点入“基金统计”查看的，但现在“基金统计”被收入二级菜单了。

一些例子：
1. 设置菜单栏显示的收益情况为【具体哪个钱包】或是【所有钱包总和】。
2. 打开后的默认界面可以设置为除【单个钱包具体情况】之外的其他页面，如【基金统计】。

可以的话十分感谢！

**Comment by 1zilc** [comment]
#357 v5.5.0 已支持菜单栏总收益显示，感谢反馈
