### ISSUE TITLE
能不能添加 一个持仓收益详情

### ISSUE THREAD

**Issue by zxpdmw** [1zilc/fishing-funds#353]
### 详细描述
根据 录入的基金的份数和成本金额 计算出当时购买基金花了多少钱
然后在根据。每天的实时净值计算出 持仓收益 
这样感觉可以更直观一点

**Comment by zxpdmw** [comment]
根据每天的实时收益计算出 当前持有基金的价值。然后根据买入的时花的钱 计算出。持仓收益

**Comment by 1zilc** [comment]
现在不是已经有这个功能吗

**Comment by zxpdmw** [comment]
![image](https://user-images.githubusercontent.com/51427547/149922447-f3a954ad-d7d0-4161-886f-1cc3618c2221.png)
这个收益估算 是前一天的收益   并不是持仓总盈亏

**Comment by zxpdmw** [comment]
![Screenshot_20220118_184619_com eastmoney android](https://user-images.githubusercontent.com/51427547/149922948-edebfba4-bb53-4e55-bb3e-0decaf716940.jpg)
像天天基金这样

**Comment by 1zilc** [comment]
持仓收益在统计里面能看到

**Comment by zxpdmw** [comment]
好的看到了，但是感觉放在首页 会更好一点。。。
