### ISSUE TITLE
建议提供宽屏版

### ISSUE THREAD

**Issue by indextank** [1zilc/fishing-funds#36]
保持现有界面的同时，建议提供宽屏版，设置里面切换
毕竟宽屏版本查看各基金信息更加具体方便。
另外，查看板块行情展示，目前的一直往下翻找查看，很不方便；
如果是宽屏，就可以提供柱状图展示，便于一眼就知道哪个版本涨的最好，哪个版本最差。
![image](https://user-images.githubusercontent.com/6389841/118793204-f5b33880-b8ca-11eb-9c9f-f936f1301e8e.png)
![image](https://user-images.githubusercontent.com/6389841/118793247-01066400-b8cb-11eb-8b09-05ae4674f98f.png)

可以参考：https://chrome.google.com/webstore/detail/%E8%87%AA%E9%80%89%E5%9F%BA%E9%87%91%E5%8A%A9%E6%89%8B-%E5%AE%9E%E6%97%B6%E6%9F%A5%E7%9C%8B%E5%9F%BA%E9%87%91%E6%B6%A8%E8%B7%8C%E5%B9%85/dhdelcemeednchdmijiocipbjlknndff
这个软件就非常不错，但是是浏览器插件，没有客户端形式方便。但是很多功能以及展示值得借鉴，很优秀的

**Comment by indextank** [comment]
抱歉，我表达的不太清楚。其实我想说的是，设置个宽屏模式，那么数据展示方式肯定是要调整变化，适应宽屏的。
而不是目前的仅仅只是将屏幕拉宽，哈哈哈哈

**Comment by 1zilc** [comment]
确实，现目前的设计只是做布局的响应式，内容的增多暂时还不考虑开发。
