### ISSUE TITLE
表单列宽自适应

### ISSUE THREAD

**Issue by Aliom252181** [1zilc/fishing-funds#362]
### 详细描述
![image](https://user-images.githubusercontent.com/49222345/151275369-0808fdef-dab0-4ae6-a5c6-5aaa6d1d8145.png)
例如这里，对基金名字还是很关系的，还有南北向那里对于买入板块，金额都是很关系的，目前只能靠拖动整个框变大才能展示完全，但是这样也会导致新闻里面变大，主页面美观度下降。
能否增加手动拖动或者增加类似的配置项决定哪些展示哪些不展示呢。
最后新年快乐～

**Comment by 1zilc** [comment]
有兴趣PR吗🤪

**Comment by Aliom252181** [comment]
@1zilc 框架不熟🤪
