### ISSUE TITLE
是否可以增加加减仓功能

### ISSUE THREAD

**Issue by B0y1n4o4** [1zilc/fishing-funds#374]
### 详细描述

希望增加一个基金加减仓（或者一键加减仓）功能，加多少，或者减多少，加（减）完之后，应该可直接计算份额成本价，等效于直接修改份额，成本价，应该不需要数据库支持

**Comment by 1zilc** [comment]
感谢建议，不过没有当天的净值，没法计算加多少钱，定投功能也是同理。
