### ISSUE TITLE
希望可以针对出一个持仓钱包的行业布局比例图

### ISSUE THREAD

**Issue by yangminghao529** [1zilc/fishing-funds#402]
希望可以针对出一个持仓钱包的行业布局比例图，就像某个特定基金那样，可以显示自己钱包里面不同行业布局的占比比例，非常感谢作者做出这么好用的APP

**Comment by 1zilc** [comment]
每个基金的规模不同，无法在现有接口基础上计算出钱包中所有板块的比例，感谢你的建议
<img width="692" alt="image" src="https://user-images.githubusercontent.com/44715458/167380693-f1124aa7-88fd-48b7-a3f9-12b885a18778.png">
