### ISSUE TITLE
场内基金ETF没有当日数据

### ISSUE THREAD

**Issue by KevinLex** [1zilc/fishing-funds#403]
### BUG 截图
所有的场内基金EFT只有昨天的数据，没有当天的净值估算。

### 详细描述
比如基金：513100，纳指EFT，能够搜到并添加到列表，但是没有当天的净值估算。
数据源都切了一遍，都没有。
上天天基金app上搜了一下这些基金，都有数据的。
没有开代理。

**Comment by 1zilc** [comment]
qdii 类基金没有估值
<img width="703" alt="image" src="https://user-images.githubusercontent.com/44715458/161175245-1227ffb4-b0bf-4aca-b316-119af7754b12.png">

**Comment by KevinLex** [comment]
看了一下，手机端有，应该是用的分时图。电脑端你截图这个地方我也点进去仔细找了一下，要点旁边的那个分时图，进去就是实时的了。

**Comment by 1zilc** [comment]
ok，可以试试把ETF的QDII基金爬到

**Comment by 1zilc** [comment]
#440 6.0.1已经修复ETF数据，感谢你的反馈！
