### ISSUE TITLE
希望能增加黄金之类的贵金属

### ISSUE THREAD

**Issue by Felix2yu** [1zilc/fishing-funds#407]
### 详细描述
可供参考数据源：
[BullionVault](https://zh-hans.bullionvault.com/gold-price-chart.do)
[工商银行](https://m.icbc.com.cn/WapDynamicSite/Windroid/GoldMarket/AccResponse.aspx)
[东方财富网](http://quote.eastmoney.com/center/hjsc.html)

**Comment by 1zilc** [comment]
#408 6.0.0已添加该模块，感谢你的反馈
