### ISSUE TITLE
基金添加不了 - 默认基金选项

### ISSUE THREAD

**Issue by indextank** [1zilc/fishing-funds#42]
![image](https://user-images.githubusercontent.com/6389841/119266834-ef9cbf00-bc1e-11eb-9b3b-c98c7cc6ed1e.png)

**Comment by 1zilc** [comment]
https://github.com/1zilc/fishing-funds/issues/29#issuecomment-834227370

**Comment by indextank** [comment]
> [#29 (comment)](https://github.com/1zilc/fishing-funds/issues/29#issuecomment-834227370)

我前两天反馈期望增加宽屏布局建议的时候，不是提到过一个chrome插件嘛，那个就可以添加，而且显示更新净值。
想必还是有办法做到的，您这边可以研究下哦~~
另外，QDII的也是无法添加的

**Comment by 1zilc** [comment]
011630是新发🐔，之前没有估值信息，我刚才测试了一下，现在已经可以正常添加了 #29
