### ISSUE TITLE
Linux版appimage无法运行

### ISSUE THREAD

**Issue by indextank** [1zilc/fishing-funds#421]
### Fishing Funds 版本号
5.7.2

### BUG 截图
![image](https://user-images.githubusercontent.com/6389841/163094262-01d7636f-9098-47cc-a83a-ac5224749377.png)

**Comment by 1zilc** [comment]
electron 18，19可能存在这个问题，尝试一下新版 #481 6.2.0，再有问题的话，提供一下操作系统平台版本号
