### ISSUE TITLE
希望可以加入“导入导出股票的json配置”功能

### ISSUE THREAD

**Issue by 1amfine2333** [1zilc/fishing-funds#458]
### 详细描述
和录入/复制基金的json的相似
<img width="196" alt="image" src="https://user-images.githubusercontent.com/24676292/172512938-b6eaa075-3247-450d-a05c-8a15c5c9d5a0.png">
如果可以对底栏排序就更好了
<img width="300" alt="image" src="https://user-images.githubusercontent.com/24676292/172513101-d7950b31-4f92-45eb-8ce8-3b53df2b1212.png">

**Comment by 1zilc** [comment]
感谢建议，[下个版本](https://github.com/1zilc/fishing-funds/pull/450)可以考虑加入

**Comment by 1amfine2333** [comment]
ok

**Comment by 1zilc** [comment]
#450 6.0.1已支持底栏排序，股票导出由于股票导入时需要一个市场id，单一的个股代码无法识别，比如茅台 secid为 1.600519，如果导入code为600519，那么就查不出来，市场id对于大部分人来说是完全没法获取的，比如美股的部分股票secid是10几开头等等，所以关于股票的导入导出就不再开发了。

**Comment by 1amfine2333** [comment]
tql ! ! !(破音)
