### ISSUE TITLE
中概互联网ETF(股票代码:513050) 添加自选股票搜索不到

### ISSUE THREAD

**Issue by augusl** [1zilc/fishing-funds#460]

**Comment by 1zilc** [comment]
这个是属于基金，不是股票
<img width="320" alt="image" src="https://user-images.githubusercontent.com/44715458/172554706-a571e0a4-bbe5-41f1-8c5f-e294d39fe1f9.png">

**Comment by augusl** [comment]
这是场内基金ETF啊,跟股票一样交易

**Comment by augusl** [comment]
> 这个是属于基金，不是股票 <img alt="image" width="320" src="https://user-images.githubusercontent.com/44715458/172554706-a571e0a4-bbe5-41f1-8c5f-e294d39fe1f9.png">
这是场内基金ETF啊,跟股票一样交易 @1zilc

**Comment by 1zilc** [comment]
接口是这样子返回的。

**Comment by augusl** [comment]
![bAO6Wig](https://i.imgur.com/bAO6Wig.png)
![b2ot46c](https://i.imgur.com/b2ot46c.jpg)

@1zilc

**Comment by 1zilc** [comment]
<img width="1468" alt="image" src="https://user-images.githubusercontent.com/44715458/172556824-d643ce41-0964-484b-89af-87ceb377eca8.png">
天天的接口给他的分类就是基金

**Comment by augusl** [comment]
好的 明白了
