### ISSUE TITLE
可以增加价钱涨跌到设置价钱的提醒吗？这个很需要。不用时刻盯着价格和手机上每次设置价格。

### ISSUE THREAD

**Issue by y1324** [1zilc/fishing-funds#462]
### 详细描述
可以增加价钱涨跌到设置价钱的提醒吗？这个很需要。不用时刻盯着价格和手机上每次设置价格。

**Comment by 1zilc** [comment]
可以设置净值提醒

**Comment by y1324** [comment]
> 可以设置净值提醒

股票的，不是基金 / 苦笑

**Comment by 1zilc** [comment]
感谢建议，[8.0.0](https://github.com/1zilc/fishing-funds/releases/tag/v8.0.0) 已支持该功能
