### ISSUE TITLE
brew 升级 404

### ISSUE THREAD

**Issue by augusl** [1zilc/fishing-funds#468]
### 详细描述
fishing-funds (6.0.2) != 6.1.0
==> Casks with 'auto_updates true' or 'version :latest' will not be upgraded; pass `--greedy` to upgra
==> Upgrading 1 outdated package:
fishing-funds 6.0.2 -> 6.1.0
==> Upgrading fishing-funds
==> Downloading https://github.com/1zilc/fishing-funds/releases/download/v6.1.0/Fishing-Funds-6.1.0.dm
curl: (22) The requested URL returned error: 404

**Comment by 1zilc** [comment]
6.1.0 的release 撤回了，6.1.1的pr还没通过 https://github.com/Homebrew/homebrew-cask/pull/126051

**Comment by augusl** [comment]
好的
