### ISSUE TITLE
全局配置支持本地路径

### ISSUE THREAD

**Issue by any-u** [1zilc/fishing-funds#478]
全局配置能否支持本地路径的配置文件，这样可以通过同步配置文件的方式实现设备同步
引自：#169

**Comment by 1zilc** [comment]
感谢你的建议，我觉得非常不错，但是实际情况可能是，受到设备系统差异的影响，这种同步方案可能只在相同系统之间会有作用，因为“本地路径的配置”这个也属于配置的一部分，举个例子：在mac中指定了路径然后备份，在linux上或者windows上使用这个备份文件可能会没有这个路径。

**Comment by any-u** [comment]
@1zilc 我理解你关于设备系统差异的影响，但我没理解你提出的那个破坏性大的解决方案，我在此描述下我的想法。
我个人有多台mac，但我想做到数据同步，比如说我在其中一台设备上手动修改了昨天的操作，可以在另一台电脑可以实时看到数据变化，而不需要再去添加一次。
如果存在读取本地配置文件的功能，我可以在我的icloud中设置一个文件，指定这个文件路径到软件里，另一台电脑可能比如说账户名不同，其实路径也不同，我只需要配置适合另一台电脑的路径，这样就可以做到实时数据同步。

windows 我知道可以通过oneDrive实现相同的功能，甚至可以与mac打通。

你提到了设备差异的影响，其中表达出了可以配置路径，那不就可以做到我所说的这点吗？
然后我就没明白你提出的那个破坏性大的解决方案，是指我描述的这样么？

**Comment by 1zilc** [comment]
<img width="618" alt="image" src="https://user-images.githubusercontent.com/44715458/178941092-c02a62d8-5e47-4d6b-8c3f-afa165cd6fe7.png">
B电脑采用了A电脑上传的配置后，路径会被替换掉

**Comment by 1zilc** [comment]
路径配置如果放在总配置里面这里需要单独处理，如果不放在总配置里面，需要单独存放，对原来的配置加载逻辑都有一定破坏性

**Comment by any-u** [comment]
很抱歉，我依旧没理解，可能对这里的总配置的概念不太理解吧。

> 好像明白了，你的想法是我想缓存整个软件的配置项吗？是吗？
> 不不不，我只是想缓存基金JSON配置

附上可以解决的方案：
简单看了下代码，config的存储是用的electron-store，位置是由electron-store决定。看了下electron-store的api，它提供cwd这个参数来修改默认存储位置，你只需要在配置界面暴露一个输入框，用于输入打算存储基金的JSON文件位置。

我在电脑A配置好路径， 电脑B我重新配置一个新的路径。至于这路径下对应的json文件内容，软件不需要去关注，至于内容如何同步，那就是用户使用不同工具的问题。

对我而言，当基金操作后，我只需要在电脑A上修改配置，程序帮我把新的数据写入路径对应的文件，icloud会帮我备份这个文件，在电脑B，我就可以直接看到最新的基金数据(操作后)。

另外至于电脑A与电脑B的路径，放你的总配置就好了，我不需要同步这个总配置项，即使后面有个电脑C，这个配置默认就为空即可。我自己手动加入就好。

> 怪我没描述清楚，我标题的全局配置指的是基金的JSON配置，不是软件的配置。
> 个人而言，我觉得程序的配置没必要同步，最多支持导出导入即可，程序配置一般较长的时间不会变动。

**Comment by 1zilc** [comment]
cwd都变了，其他的配置也会跟着变呀 🤔

**Comment by 1zilc** [comment]
我之前也想过用localstorage来单独存放这个配置路径，其他的所有配置用electron-store存，但是下个版本的多窗口功能会出现一个兼容问题。目前还没有想到好的解决方案。我再想想吧

**Comment by any-u** [comment]
ok，详细设计点我并不了解，也没太多时间去看具体的代码。那就期待你的方案吧

**Comment by 1zilc** [comment]
#481 6.2.0已支持配置同步，感谢你的建议
