### ISSUE TITLE
能否加入基金分红功能

### ISSUE THREAD

**Issue by Secret-Zero227** [1zilc/fishing-funds#485]
能否考虑基金分红合并入持有收益中

**Comment by Secret-Zero227** [comment]
举例说明：假设您现持有金鹰中小盘10000万基金份额， 除息后的基金份额净值为1.42元，其收益分配方案是每10 份基金份额派发红利0.60元（即分红比例为：=0.6/10=0.06）。则：
分红的金额为=10000*0.06=600元；
　　新增份额=分红金额/除息后的基金份额净值=600/1.42=422.53份；
　　A)若选择领取现金：则总份额不变，直接通过银行账号领取现金600元，单位净值：=1.42元。
　　B)若选择分红再投资：则新增422.53份，总份额=10000+422.53=10422。53份，单位净值：=1.42元。

可能需要设置分红方式，如果是a的话，直接将持有收益加上分红额就可，b的话还得增加持有份额

**Comment by 1zilc** [comment]
A方案：这个分红金额在ff中不会纳入持有收益，就像你在高点卖出在低点买入后，ff不会记录之前的累积收益，只能记录当前的持有份额的收益情况。
B方案：分红后，基金净值会发生变化，份额会变多，所以重新输入新的份额和净值即可。

类似于累计收益，分红收益，定投之类的功能，受限于FF本身只是个看估值的纯前端工具，实现起来难度太大，意义也不太大，就没有开发的打算，🙏谅解哈

**Comment by Secret-Zero227** [comment]
好的，感谢回答啦
