### ISSUE TITLE
无法新增股票

### ISSUE THREAD

**Issue by artNcoder** [1zilc/fishing-funds#486]
### Fishing Funds 版本号
V6.1.1

### 操作系统平台及版本号
macOS
12.4 (21F79)

### BUG 截图
<img width="313" alt="image" src="https://user-images.githubusercontent.com/2703752/180376871-00a03598-9f99-4b56-8f9e-0c43093fa306.png">

### 详细描述
输入股票代码后，点击搜索无反应

**Comment by 1zilc** [comment]
可能是网络原因，目前是能搜索到的
<img width="320" alt="image" src="https://user-images.githubusercontent.com/44715458/180385461-d2582bb5-c409-42c6-8beb-b9413c1d84a4.png">

**Comment by artNcoder** [comment]
> 可能是网络原因，目前是能搜索到的 <img alt="image" width="320" src="https://user-images.githubusercontent.com/44715458/180385461-d2582bb5-c409-42c6-8beb-b9413c1d84a4.png">

好的，刚刚试了一下，开了VPN，基金可以添加，股票无法添加，数据都可以同步。关掉VPN就可以添加股票了。

**Comment by 1zilc** [comment]
好的，那我关闭了哈
