### ISSUE TITLE
部分基金还是添加不了，比如011399

### ISSUE THREAD

**Issue by indextank** [1zilc/fishing-funds#52]
其他软件可以添加，可以查收益，都正常。
![image](https://user-images.githubusercontent.com/6389841/120782633-c6542b00-c55c-11eb-8119-199969477bcc.png)

**Comment by indextank** [comment]
![image](https://user-images.githubusercontent.com/6389841/120782791-f00d5200-c55c-11eb-8ca7-0d39a825d37e.png)


软件都是3.1.0最新版，刚刚升级的

**Comment by 1zilc** [comment]
请按照模版提交反馈

**Comment by indextank** [comment]
啥模板？

**Comment by 1zilc** [comment]
issues 模版

**Comment by 1zilc** [comment]
011399 这个也是个新发🐔，天天上什么时候有估值的什么时候才能添加。

**Comment by 1zilc** [comment]
040046 可以添加
![image](https://user-images.githubusercontent.com/44715458/120783399-935e6700-c55d-11eb-8e92-096aaf093d29.png)

**Comment by indextank** [comment]
抱歉，我默认进来的不知道咋跳过选择模板哪一个步骤了。。后面会注意的。
011399 其他chrome插件是可以查看收益的，每天的，
![image](https://user-images.githubusercontent.com/6389841/120783548-bb4dca80-c55d-11eb-9add-7ff3b071b6cd.png)

**Comment by 1zilc** [comment]
东财这个现在可以添加了啊

**Comment by 1zilc** [comment]
011399 确实还不行
