### ISSUE TITLE
请解释下这是什么情况！这不是后门吗

### ISSUE THREAD

**Issue by JasonYHZ** [1zilc/fishing-funds#527]
为什么你们这个app，会偷偷的一直在请求这些网址。能给个解释吗
<img width="608" alt="image" src="https://user-images.githubusercontent.com/18589230/194883945-bb67a104-9415-4647-8b01-a53fd861d3a5.png">
<img width="954" alt="image" src="https://user-images.githubusercontent.com/18589230/194883984-495bedc6-100c-48b5-b54c-1be8c8a543e5.png">
<img width="897" alt="image" src="https://user-images.githubusercontent.com/18589230/194884060-79b5644c-c31a-4bb0-b556-f3e76a9c9101.png">
<img width="832" alt="image" src="https://user-images.githubusercontent.com/18589230/194884096-5a910157-f310-423f-b419-5652b750ed11.png">
<img width="668" alt="image" src="https://user-images.githubusercontent.com/18589230/194884123-55297ee8-fb01-4054-809e-d6b3245135bc.png">

**Comment by georgemarsroberts** [comment]
没偷你其他信息就不错啦，当你肉鸡刷刷广告而已啦😂

**Comment by 1zilc** [comment]
原本京东的时间戳接口失效了而已，现在被重定向到京东首页了

**Comment by JasonYHZ** [comment]
好
