### ISSUE TITLE
考虑下改回折线图的方式么

### ISSUE THREAD

**Issue by cx2c** [1zilc/fishing-funds#548]
### 详细描述
<img width="325" alt="image" src="https://user-images.githubusercontent.com/13431516/201282065-a5cca1a7-3ecb-440f-b9f4-3bc57b65d58e.png">

一直使用旧版的，能清晰看到当日走势。新版的不太友好，能否给个配置选项呢？

**Comment by 1zilc** [comment]
有没有一种可能，板了的票它的走势就是这样子的

**Comment by cx2c** [comment]
> 板了的票它的走势就是这样子的

<img width="325" alt="image" src="https://user-images.githubusercontent.com/13431516/201295452-207d0162-7f1b-492c-ae53-bc0a53c8c7c2.png">
现在是这样的，看不到趋势

**Comment by 1zilc** [comment]
<img width="439" alt="image" src="https://user-images.githubusercontent.com/44715458/201309980-6a81fc8b-df05-4754-9b63-83e0d64d9184.png">
这里可以切换

**Comment by cx2c** [comment]
> <img alt="image" width="439" src="https://user-images.githubusercontent.com/44715458/201309980-6a81fc8b-df05-4754-9b63-83e0d64d9184.png">
> 
> 这里可以切换

😳 还以为这个icon是  这个下拉菜单的icon
<img width="342" alt="image" src="https://user-images.githubusercontent.com/13431516/201312921-79790001-1ab6-4313-910f-2b1272955f78.png">

**Comment by 1zilc** [comment]
用强调色的地方理论上都是可以点击的哈

**Comment by cx2c** [comment]
不得不夸一句，软件做的太棒了～  已经安利好几个同事用上了
