### ISSUE TITLE
封闭基金不展示实时收益

### ISSUE THREAD

**Issue by wang2** [1zilc/fishing-funds#566]
### Fishing Funds 
版本号 7.1.0

### 操作系统平台及版本号 
macOS 13.2.1 (22D68)

### BUG 截图
<img width="318" alt="image" src="https://user-images.githubusercontent.com/5775006/220222720-36f61b9b-1f37-49ea-9d4e-b92d6015ed7a.png">

### 详细描述
目前的现象：封闭基金不展示实时收益
可以改进的地方：即使是封闭基金也会披露净值，因此也可以披露实时收益

**Comment by 1zilc** [comment]
抱歉，天天基金数据源没这个基金的数据，无法支持
![image](https://user-images.githubusercontent.com/44715458/220496291-a62b35c1-285d-4ead-bec5-78e14eb50928.png)
