### ISSUE TITLE
能在提供 类似手机 widget的功能  在电脑上面吗

### ISSUE THREAD

**Issue by bombmanbombman** [1zilc/fishing-funds#574]
### 详细描述
能在提供 类似手机 widget的功能  在电脑上面吗？就是类似以前windows8 时钟 天气的 小插件，在桌面一直显示。
桌面版，每次都要去taskbar 这里点击，鼠标移开了又自动隐蔽了，不方便。还是有其他的操作方式？

**Comment by 1zilc** [comment]
感谢你的建议，但是这个软件设计就是如此
