### ISSUE TITLE
在合适的位置引入开盘啦直播

### ISSUE THREAD

**Issue by zanderzhng** [1zilc/fishing-funds#587]
### 详细描述

https://www.kaipanla.com/index.php/live/index
浏览器访问需要屏蔽掉 kaipanla.com###w-dialog-login 这个元素，可以用adblock在黑名单试试。

<img width="681" alt="image" src="https://user-images.githubusercontent.com/867749/230530012-ebecf67d-48c3-480f-b1f6-eb01a5fcb6df.png">

**Comment by 1zilc** [comment]
感谢你的建议，这个可以用H5自己添加就行了，或者要是有接口我可以考虑集成一下

**Comment by zanderzhng** [comment]
> 感谢你的建议，这个可以用H5自己添加就行了，或者要是有接口我可以考虑集成一下

直接用app访问这个链接，会进入到手机页面，看不到内容。估计要改 useragent。

**Comment by 1zilc** [comment]
<img width="171" alt="image" src="https://user-images.githubusercontent.com/44715458/230573174-b0f9ea0f-15ad-45e1-9edf-2005d1853dcf.png">
可以试试把移动端标识关闭然后重新打开页面
