### ISSUE TITLE
下载的安装包打开提示：未能打开磁盘映像；磁盘映像已损坏

### ISSUE THREAD

**Issue by xiaohundun** [1zilc/fishing-funds#589]
### Fishing Funds 版本号
7.2.0
### 操作系统平台及版本号
M1P
### BUG 截图
<img width="260" alt="image" src="https://user-images.githubusercontent.com/38812912/231067278-c83b1d00-702b-42d4-bef6-95f12d72fc66.png">

**Comment by 1zilc** [comment]
请尝试重新下载
