### ISSUE TITLE
NSIS Error

### ISSUE THREAD

**Issue by ReidNeargo** [1zilc/fishing-funds#592]
### Fishing Funds 版本号
7.2.0
### 操作系统平台及版本号
版本	Windows 11 家庭中文版
版本	22H2
安装日期	‎2022/‎10/‎23
操作系统版本	22621.1413

### 详细描述
Installer integrity check has failed. Common causes includeincomplete download and damaged media. Contact theinstaller's author to obtain a new copy.
More information at.http.//nsis.sf.net/NSIS Error

**Comment by 1zilc** [comment]
检查安装包的完整性
```bahs
# MD5
06d11d2117cf178eecf1958d371e5a32
```
<img width="384" alt="iShot_2023-04-21_11 03 08" src="https://user-images.githubusercontent.com/44715458/233531218-0ecce31e-b5db-4641-a8d7-5d7a1bf170a6.png">

**Comment by ReidNeargo** [comment]
> 检查安装包的完整性
> 
> ```
> # MD5
> 06d11d2117cf178eecf1958d371e5a32
> ```
> 
> <img alt="iShot_2023-04-21_11 03 08" width="384" src="https://user-images.githubusercontent.com/44715458/233531218-0ecce31e-b5db-4641-a8d7-5d7a1bf170a6.png">

是从官网下载的
