### ISSUE TITLE
同一个基金不同时期买入，没办法加俩个条数据看收益？

### ISSUE THREAD

**Issue by simosun** [1zilc/fishing-funds#615]
### 详细描述
同一个基金不同时期买入，价格和份额不一样，没办法分别这个基金的收益？

**Comment by 1zilc** [comment]
可以创建另一个钱包添加

**Comment by simosun** [comment]
不好意思，我眼拙，没找到怎么添加钱包，我只有一个默认钱包

**Comment by 1zilc** [comment]
<img width="185" alt="image" src="https://github.com/1zilc/fishing-funds/assets/44715458/7404b442-7367-4136-8bcf-ad9b2937280d">
