### ISSUE TITLE
求一个基金净值估算的功能

### ISSUE THREAD

**Issue by Youngmiyo** [1zilc/fishing-funds#633]
### 详细描述
搞不懂这些👻为什么要下线估算，很🔥大，直接瞎眼了，都去买指数得了

不知道作者是否考虑出个净值估算的功能，刚需

**Comment by 1zilc** [comment]
参考涨幅估算

**Comment by Youngmiyo** [comment]
> 参考涨幅估算

主动基金好些都参考不了了啊，估计是逐步下线了，指数也不会在场外买

**Comment by Youngmiyo** [comment]
> > 参考涨幅估算
> 
> 主动基金好些都参考不了了啊，估计是逐步下线了，指数也不会在场外买

根据持仓自己估算？？？那根本是瞎子，能10%的准确率就很牛了

**Comment by 1zilc** [comment]
我的意思是现在本身就能看涨幅啊

**Comment by 1zilc** [comment]
你要的是净值估算，这个意义不大，净值一般就1.几，高一点的就3左右，一天涨幅也就1到2%，基本不怎么变的

**Comment by Youngmiyo** [comment]
> 你要的是净值估算，这个意义不大，净值一般就1.几，高一点的就3左右，一天涨幅也就1到2%，基本不怎么变的

对于主动基金来说尤其是固收+基金的意义还是蛮大的，比如我会根据估算来判断今天是否加仓，因为一些固收+的主动基金是比较有迹可循的，跌幅空间有限，涨幅空间也有限，就是波动率不大，且我这个固收+就适合一段时间的高抛低吸，所以我好根据当日的净值估算来加减仓操作，虽然估值可能会不太准，但也是提高准确率的一个重要指标，我一直根据估值和持仓的涨幅来判断当日的最终净值，准确率80%

**Comment by 1zilc** [comment]
波动率不大，可以根据前一日的净值来操作

**Comment by 1zilc** [comment]
你直接上个代码吧，我看看是哪只

**Comment by Youngmiyo** [comment]
> 波动率不大，可以根据前一日的净值来操作

唉~008810安信民稳增长混合C，天天基金和支付宝都下线了它的估算，我日常只用这两个平台的估算，因为比较准

**Comment by 1zilc** [comment]
我觉得前一日的净值+今日的涨跌幅，就能操作了呀
<img width="320" alt="image" src="https://github.com/1zilc/fishing-funds/assets/44715458/3154009f-81f2-41f4-bd3e-ed417acecf08">
今日净值估算也就是 前一日的净值和今日的涨跌幅 算出来的

**Comment by Youngmiyo** [comment]
> 我觉得前一日的净值+今日的涨跌幅，就能操作了呀
> <img alt="image" width="320" src="https://user-images.githubusercontent.com/44715458/255456317-3154009f-81f2-41f4-bd3e-ed417acecf08.png">
> 今日净值估算也就是 前一日的净值和今日的涨跌幅 算出来的

净值估算我不知道是怎么算出来的，真的是前一日净值和今日涨跌幅？今日的涨跌幅你指的是实时的还是收盘之后的，收盘之后没意义啊，加减仓操作肯定是尾盘在最后5分钟的，你这个涨跌幅是同花顺的接口数据吧，我暂时切换了同花顺的数据看估算，但我知道同花顺的准确率极低，且应该也会不久后跟着下线

**Comment by 1zilc** [comment]
下版本可以加上，这个数据在接口里是有的，目前没有展示，感谢建议

**Comment by 1zilc** [comment]
今日的涨跌幅 就是实时的

**Comment by 1zilc** [comment]
净值估算 = 昨日净值 *（1+今日的涨跌幅）%

**Comment by Youngmiyo** [comment]
> 下版本可以加上，这个数据在接口里是有的，目前没有展示，感谢建议

🤩好好好，感谢，天天基金接口数据里还有这个稳增长C的就非常棒了

> 今日的涨跌幅 就是实时的

今日涨跌幅实时这个东西主动型基金也会有？不是指数才会有这东西吗？

> 净值估算 = 昨日净值 *（1+今日的涨跌幅）%

👍🏻我没去研究这个，只是对比过天天基金和支付宝的估算是准确率很高的，偏差也很小

**Comment by 1zilc** [comment]
8.1.0 已支持 https://github.com/1zilc/fishing-funds/pull/638
