### ISSUE TITLE
所有的指数、板块内容都无法看到了

### ISSUE THREAD

**Issue by smallwonton2019** [1zilc/fishing-funds#637]
### Fishing Funds 版本号
8.0.1
### 操作系统平台及版本号
macos12
### BUG 截图
![image](https://github.com/1zilc/fishing-funds/assets/56538819/9221de11-15b0-4db6-bb07-0da5c52faf2c)
![image](https://github.com/1zilc/fishing-funds/assets/56538819/1e3f6dba-3624-4696-a5e6-5a6ec4a699d3)

### 详细描述
所有的指数、板块内容都无法看到了

**Comment by 1zilc** [comment]
检查自己的网络

**Comment by smallwonton2019** [comment]
> 检查自己的网络或者关闭代理

好的，由于代理问题，已处理，感谢作者
