### ISSUE TITLE
非常不错的软件，有几个小建议

### ISSUE THREAD

**Issue by NapChen** [1zilc/fishing-funds#645]
### 详细描述
1、顶部增加上证指数的显示，二不必切换到指数tab才能看到
2、基金和股票的收益能否分开一个合计，即基金合计，股票合计以及总计
3、股票当前价格能够固定保留两位小数，不然看着有点参差不齐

感谢作者为爱发电

**Comment by 1zilc** [comment]
1. macbook touchbar能显示第一个指数
2. 鼠标指上去会显示分开合计
3. 不能
