### ISSUE TITLE
透明度

### ISSUE THREAD

**Issue by WZhuang-NiLiuSha** [1zilc/fishing-funds#654]
### 详细描述
低调模式下透明度 太透明了 看不清 可以调不

**Comment by 1zilc** [comment]
设置-低调程度

**Comment by geeklihui** [comment]
@1zilc 但是只想要像以前一样变灰，不想透明，透明实在是看不清，调整低调程度后能看清了但也不是灰色了。还能改回去吗 ㄒ_ㄒ

**Comment by 1zilc** [comment]
8.2.0 https://github.com/1zilc/fishing-funds/pull/676 已支持单独设置，感谢建议
