### ISSUE TITLE
同花顺数据源货币基金净值获取错误

### ISSUE THREAD

**Issue by PRSJMC** [1zilc/fishing-funds#672]
### Fishing Funds 版本号
8.1.1
### 操作系统平台及版本号
Windows 10 22H2
### BUG 截图
![image](https://github.com/1zilc/fishing-funds/assets/46528990/ffb081f1-600f-4e36-bf8d-cdfe7b9441f6)
### 详细描述
同花顺数据源对货币基金获取的“净值”实际是每万份收益，导致持有收益率统计错误。

**Comment by 1zilc** [comment]
感谢反馈，8.2.0已修复 https://github.com/1zilc/fishing-funds/pull/676 ，目前逻辑和东财接口一致，无法提供数据，但修复了净值异常
