### ISSUE TITLE
是否考虑修改 增加估值收益走势图 的进入方式

### ISSUE THREAD

**Issue by Peterpig** [1zilc/fishing-funds#673]
### 详细描述

现在查看某个基金走势图要点好多下。能否直接在列表页点击直接弹出走势图弹出框。类似下面这种的

<img width="590" alt="image" src="https://github.com/1zilc/fishing-funds/assets/7956973/f65e1adc-53db-42aa-a174-4c701985ad34">

**Comment by 1zilc** [comment]
十分感谢建议，但是由于FF本身程序宽度比较狭窄，这个图其实看起来不太清楚，综合一下请求和交互逻辑方面的情况，就不支持这个功能了。。
