### ISSUE TITLE
同一基金多次购买后的收益计算

### ISSUE THREAD

**Issue by greenyi1984** [1zilc/fishing-funds#674]
当前版本似乎只支持一个基金只能设置一个成本价和份额， 然后计算收益。 但是， 如果多次购买了基金， 成本均价可以估算出来，但是收益是不同的。 
有考虑对同一个基金允许多个成本及份额的计算嘛？

**Comment by 1zilc** [comment]
如果你在同一平台多次购买相同基金，只需要设置总的份额和总的净值就行了。
不同平台购买，可以考虑多钱包功能。
