### ISSUE TITLE
持有收益计算有误

### ISSUE THREAD

**Issue by iOSleep** [1zilc/fishing-funds#675]
### Fishing Funds 版本号
v8.1.1
### 操作系统平台及版本号
MacOS 14.3.1
### BUG 截图

<img width="273" alt="QQ20240220-115035@2x" src="https://github.com/1zilc/fishing-funds/assets/26478957/d1360bb5-2650-46e6-8f44-c29854f19d23">

### 详细描述

成本低于当前价格，但是显示持有收益是负数

**Comment by 1zilc** [comment]
和基金逻辑保持一致，为上一个交易日收盘价 - 成本价
