### ISSUE TITLE
Win11，初次安装8.2.0，JS报错，无法启动

### ISSUE THREAD

**Issue by XJwangdage** [1zilc/fishing-funds#678]
### Fishing Funds 版本号
8.2.0
### 操作系统平台及版本号
Windows 11 CoreCountrySpecific 23H2 22631.3155
### BUG 截图
![](https://static.codemao.cn/xj/HkrZIxw3p.image/png)
### 详细描述
初次安装8.2.0，是全局安装，安装在D盘，非管理员与管理员模式启动均JS报错，无法启动
迫切请求修复

**Comment by 1zilc** [comment]
感谢反馈，8.2.1应该修复了 https://github.com/1zilc/fishing-funds/releases/tag/v8.2.1
