### ISSUE TITLE
跨平台配置文件同步/导入导出全局配置好像出问题了

### ISSUE THREAD

**Issue by geeklihui** [1zilc/fishing-funds#680]
### Fishing Funds 版本号
8.2.1
### 操作系统平台及版本号
macOS14 和 Win11
### BUG 截图
![image](https://github.com/1zilc/fishing-funds/assets/28993319/d31b9887-b012-486d-bbfd-f945f686d65f)

### 详细描述
之前是好好的，两边都能同步和导入导出，之后因为一些原因卸载了 macOS 上的 fishingfunds，昨天重新装回来以后，发现一直在用的同步配置文件在 macOS 这边导入以后，是空的，啥都没有。然后又去 win 那边看了一下，确认数据正常，就想说是不是同步的配置文件不适用于导入导出，就手动导出了一份全局配置，在 macOS 这边导入，结果还是空的。

**Comment by 1zilc** [comment]
感谢反馈，8.2.2 https://github.com/1zilc/fishing-funds/pull/681  应该修好了
