### ISSUE TITLE
是否有可能基金里面选择场内或场外基金？

### ISSUE THREAD

**Issue by seraphg** [1zilc/fishing-funds#682]
请问是否有可能区分场内/场外基金？现在App里面缺省应该是场外基金价格吧，是否能够选择场内还是场外基金呢？谢谢！

**Comment by Burne00** [comment]
+1

**Comment by 1zilc** [comment]
没看懂啥意思

**Comment by seraphg** [comment]
基金有分场内和场外，有一些基金有场内基金，具体介绍请见https://news.10jqka.com.cn/20211102/c633902720.shtml

<img width="715" alt="image" src="https://github.com/1zilc/fishing-funds/assets/25558367/5d869057-093a-457a-ad35-8d6ad40af03d">

在券商App上面也可以看到，比如：

![image](https://github.com/1zilc/fishing-funds/assets/25558367/fb73da37-6027-4fe7-99db-79ba5ac9c442)

场内价格和场外价格是不一样的。

希望这些说明有帮助，谢谢

**Comment by 1zilc** [comment]
如果你说的价格指估值的话，目前没有场内的接口，如果是基金录入，只涉及成本价和份额，你用场内的数据录入是一样的。
