### ISSUE TITLE
天天基金：海外基金（如 968061）数据异常

### ISSUE THREAD

**Issue by geeklihui** [1zilc/fishing-funds#683]
### Fishing Funds 版本号
8.2.3
### 操作系统平台及版本号
macOS 14.3.1
### BUG 截图
![image](https://github.com/1zilc/fishing-funds/assets/28993319/dc01f1a2-f1e9-4052-8d50-0aca8ca99a7c)
![image](https://github.com/1zilc/fishing-funds/assets/28993319/7674759b-bc25-4cba-8dc6-9b0fc819cd6a)
### 详细描述
数据源：天天基金
[968061 天天基金官网显示正常](https://overseas.1234567.com.cn/968061)
fishingfunds 中停留在 02-07 数据，点开详情后各项数据空白。

update：似乎和海外基金的天天基金域名有关系，我试了下其他基金都是直接 `fund.eastmoney.com/xxx.html`，但这个基金是 `overseas.1234567.com.cn/968061` 。手动访问 `fund.eastmoney.com/968061.html` 也会自动跳转到 `overseas.1234567.com.cn/968061`

**Comment by 1zilc** [comment]
<img width="815" alt="image" src="https://github.com/1zilc/fishing-funds/assets/44715458/7b907ff5-b912-4987-8407-231ea3ae3424">
天天基金的原始估值接口停止了对这个基金的数据更新，目前这个逻辑不好去处理，尝试一下其他数据源吧。

**Comment by geeklihui** [comment]
好的，只是根据域名推测，应该是海外基金在天天都有一样的问题，不止这一个基金。

**Comment by 1zilc** [comment]
暂时先关了，如果还有其他疑问再reopen
