### ISSUE TITLE
希望新增股票的涨跌幅榜单

### ISSUE THREAD

**Issue by mystoryshine** [1zilc/fishing-funds#685]
### 详细描述
希望新增股票的涨跌幅榜单，如果可以分主板、创业板、科创板、北交所是最好的，希望支持！

**Comment by 1zilc** [comment]
感谢建议，8.3.0 已添加更多榜单 
<img width="300" alt="image" src="https://github.com/user-attachments/assets/27d11e68-103c-48a5-b935-fe0058b208be">
