### ISSUE TITLE
基金矩阵

### ISSUE THREAD

**Issue by Chrischcc** [1zilc/fishing-funds#687]
作者大大，可以考虑优化加入基金--利率矩阵和信用矩阵吗
万分感谢🙏

**Comment by 1zilc** [comment]
这个是什么？有现成的截图或者页面吗

**Comment by Chrischcc** [comment]
> 这个是什么？有参考的截图或者页面吗

hi，是参考的东方财富有个choice软件里的一个矩阵，分为利率矩阵和信用矩阵，参考图：
![IMG_3683](https://github.com/1zilc/fishing-funds/assets/131735371/ff35cebd-1f8f-40f7-8d51-3bfac2938f10)
![IMG_3684](https://github.com/1zilc/fishing-funds/assets/131735371/8773a960-1b60-4330-9540-685df2f93f96)
![Uploading IMG_3685.PNG…]()

**Comment by 1zilc** [comment]
感谢建议 ，这个是app端的功能，目前没法通过网页的接口获取到这些数据，而且像这种比较专业的数据建议用专业软件哈，FF主要还是看估值，算收益，这个功能就不考虑了，望谅解
