### ISSUE TITLE
建议增加常用指标可选

### ISSUE THREAD

**Issue by DanileLxp** [1zilc/fishing-funds#688]
### 详细描述
建议增加可3个指标栏， VOL / MACD / WR / KDJ / RSI 这些常用指标可选

**Comment by 1zilc** [comment]
<img width="262" alt="image" src="https://github.com/1zilc/fishing-funds/assets/44715458/aeeff3b4-a51c-4a92-9847-5433b5811d7f">

**Comment by DanileLxp** [comment]
哈哈哈，晚上有看到。大佬，可以自己添加需要的指标吗
