### ISSUE TITLE
可以弄一个这种桌面表单吗

### ISSUE THREAD

**Issue by LiYuHan525** [1zilc/fishing-funds#689]
### 详细描述
<img width="83" alt="微信图片_20240607142044" src="https://github.com/1zilc/fishing-funds/assets/37262960/02755d10-0fca-4e49-ab0c-75f93cf881a7">

用来摸鱼，而且可以一直盯盘

**Comment by 1zilc** [comment]
可以试试打开这三个
<img width="251" alt="image" src="https://github.com/1zilc/fishing-funds/assets/44715458/efe16c26-3f5a-479e-bd7e-15ae16c3b84d">

**Comment by LiYuHan525** [comment]
好，感谢回复
