### ISSUE TITLE
自动刷新的刷新间隔请支持秒级配置

### ISSUE THREAD

**Issue by JoeyLearnsToCode** [1zilc/fishing-funds#695]
### 详细描述

当前自动刷新的配置单位是分钟的，哪怕最小配置为 1 分钟也不太够，股票波动比较大，1 分钟过去可能涨停变跌停了😂。
所以希望能支持秒级配置

**Comment by 1zilc** [comment]
- 高强度操作建议直接在你的股票客户端进行
- ff是爬下来的数据，大量请求会触发东财的反爬
- 请求是单个发送的，东财目前没有一次性查所有票的接口，或许有但是我没找到
