### ISSUE TITLE
今日收益率一直是0

### ISSUE THREAD

**Issue by gufeng0** [1zilc/fishing-funds#697]
### Fishing Funds 版本号
8.3.0

### 操作系统平台及版本号
macOS

### BUG 截图
<img width="325" alt="image" src="https://github.com/user-attachments/assets/0aeb5c17-cf15-495b-b5a8-6fb3e7a7447e">

### 详细描述
为啥今日收益率和旁边的金额一直是0

**Comment by 1zilc** [comment]
因为还没开盘

**Comment by gufeng0** [comment]
> 因为还没开盘

请问啥时候开盘，萌新小白不是很懂

**Comment by 1zilc** [comment]
你这个QDII 应该是没有估值的
A股和港股开盘时间自己去搜索
