### ISSUE TITLE
好应用，已收录，感谢开发者！

### ISSUE THREAD

**Issue by macwkcom** [1zilc/fishing-funds#77]
### 详细描述:  

![image](https://user-images.githubusercontent.com/53843550/122399316-43e05800-cfad-11eb-9117-4a6d5be5fb53.png)

[收录地址](https://www.macwk.com/soft/fishing-funds)

如果开发者觉得不合适，回复我一下，我把它下掉。

**Comment by 1zilc** [comment]
感谢认可和你的收录，不用下它哈，还请多多推广

**Comment by macwkcom** [comment]
> 感谢认可和你的收录，不用下它哈，还请多多推广

好嘞，哈哈
