### ISSUE TITLE
希望增加走势屏

### ISSUE THREAD

**Issue by Aliom252181** [1zilc/fishing-funds#89]
### 详细描述:  
在查看基金详情的时候，鼠标悬浮在基金上的弹窗很容易被窗口覆盖，展示不全。并且滚动事件很容易触发走势图的放大缩小。
推荐增加新屏作为备选方案。用户可以自由选择点击基金的后弹出详情的屏幕类别，为只想看大致详情的提供原有小窗体，为想体验完整数据的提供大窗体。

**Comment by Aliom252181** [comment]
OS：本来我也想改一下的，但是项目拉下来启动就费老事了，就没提PR。

**Comment by 1zilc** [comment]
欢迎PR哈，看了兄弟的掘金还是很厉害的！

**Comment by Aliom252181** [comment]
> 欢迎PR哈，看了兄弟的掘金还是很厉害的！

厉害：指大韭菜(呜呜呜～)
