### ISSUE TITLE
希望优化复制基金配置

### ISSUE THREAD

**Issue by Aliom252181** [1zilc/fishing-funds#92]
### 详细描述:  
在版本替换中可能会有不兼容的数据存在，可以导出全部配置便于版本替换和用户数据整理。
目前只能导出基金配置，希望增加导出全局配置（包含指数行情页配置）。

**Comment by 1zilc** [comment]
不太明白不兼容的数据是指什么

**Comment by Aliom252181** [comment]
> 不太明白不兼容的数据是指什么

我从4.0.1更新4.1.0的时候直接说包体损坏了（apple m1芯片）。
兼容就是有些Brock更新的时候可以保留用户配置，直接倒入导出就好了，类似于用户账户的替代方案。

**Comment by Aliom252181** [comment]
> > 不太明白不兼容的数据是指什么
> 
> 我从4.0.1更新4.1.0的时候直接说包体损坏了（apple m1芯片）。
> 兼容就是有些Brock更新的时候可以保留用户配置，直接倒入导出就好了，类似于用户账户的替代方案。

卸载安装后更新成功，直接覆盖会BUG，感谢功能更新～～

**Comment by 1zilc** [comment]
arm的覆盖安装有问题吗？我的mac不是M1没办法测试，其他平台我测试过，是没有问题

**Comment by 1zilc** [comment]
如果是git release渠道下载的，那就只可能是electron-builder的问题

**Comment by 1zilc** [comment]
全局配置的话，我考虑是做成导出配置文件，包含设置，指数和基金，其实有一套后端是最好的，但是开源的话其实不太安全，后面再考虑一下吧
